---
id_ceph:
   ceph1: 00000000-0001-0000-0000-000000000001
   ceph2: 00000000-0001-0000-0000-000000000002
   ceph3: 00000000-0001-0000-0000-000000000003


#----------------------------------------------------
#src ub18
src_ceph_ub18:
   ceph1: "10.10.3.10:6789,10.10.3.11:6789,10.10.3.12:6789"
   ceph2: "10.10.6.41:6789,10.10.6.42:6789,10.10.6.43:6789,10.10.6.44:6789,10.10.6.45:6789"
   ceph3: "10.10.7.41:6789,10.10.7.42:6789,10.10.7.43:6789,10.10.7.44:6789,10.10.7.45:6789"

#---
#src ub20-22
src_ceph_ub20:
   ceph1: "10.10.3.10:6789/10.10.3.11:6789/10.10.3.12:6789"
   ceph2:  "10.10.6.41:6789/10.10.6.42:6789/10.10.6.43:6789/10.10.6.44:6789/10.10.6.45:6789"
   ceph3: "10.10.7.4:6789/10.10.7.42:6789/10.10.7.43:6789/10.10.7.44:6789/10.10.7.45:6789"

